import { useEffect, useRef, useState } from "react";
import { arrayUnion, collection, doc, onSnapshot, query, setDoc, where } from "firebase/firestore";
import { db } from "./firebase";

type CallProfile={uid:string;username:string;avatar:string;photoURL?:string};
type Props={user:{uid:string}|null;selected:CallProfile|null};

type CallDoc={callerId:string;calleeId:string;callerName:string;calleeName:string;type:"voice"|"video";offer?:RTCSessionDescriptionInit;answer?:RTCSessionDescriptionInit;callerCandidates?:RTCIceCandidateInit[];calleeCandidates?:RTCIceCandidateInit[];status?:string};

export default function CallControls({user,selected}:Props){
 const pc=useRef<RTCPeerConnection|null>(null),local=useRef<MediaStream|null>(null),remote=useRef<MediaStream|null>(null),callId=useRef("");
 const [incoming,setIncoming]=useState<CallDoc|null>(null),[incomingId,setIncomingId]=useState(""),[active,setActive]=useState<"voice"|"video"|null>(null),[muted,setMuted]=useState(false),[camera,setCamera]=useState(true),[error,setError]=useState("");
 const cleanup=()=>{pc.current?.close();pc.current=null;local.current?.getTracks().forEach(t=>t.stop());local.current=null;remote.current?.getTracks().forEach(t=>t.stop());remote.current=null;callId.current="";setActive(null);setMuted(false);setCamera(true)};
 useEffect(()=>{if(!user)return;const q=query(collection(db,"calls"),where("calleeId","==",user.uid),where("status","==","ringing"));return onSnapshot(q,s=>{const d=s.docs[0];if(d&&!active){setIncoming(d.data() as CallDoc);setIncomingId(d.id)}},()=>{});},[user,active]);
 useEffect(()=>()=>cleanup(),[]);
 const start=async(type:"voice"|"video")=>{if(!user||!selected||active)return;try{setError("");const stream=await navigator.mediaDevices.getUserMedia({audio:true,video:type==="video"});local.current=stream;const r=new RTCPeerConnection({iceServers:[{urls:"stun:stun.l.google.com:19302"}]});pc.current=r;stream.getTracks().forEach(t=>r.addTrack(t,stream));const ref=doc(collection(db,"calls"));callId.current=ref.id;r.onicecandidate=e=>{if(e.candidate)setDoc(ref,{callerCandidates:arrayUnion(e.candidate.toJSON())},{merge:true})};r.ontrack=e=>{remote.current=e.streams[0]||null};const offer=await r.createOffer();await r.setLocalDescription(offer);await setDoc(ref,{callerId:user.uid,calleeId:selected.uid,callerName:"",calleeName:selected.username,type,offer,status:"ringing",callerCandidates:[],calleeCandidates:[]});setActive(type);const unsub=onSnapshot(ref,s=>{const d=s.data() as CallDoc|undefined;if(!d)return;if(d.answer&&!r.currentRemoteDescription)r.setRemoteDescription(new RTCSessionDescription(d.answer));(d.calleeCandidates||[]).forEach(c=>r.addIceCandidate(new RTCIceCandidate(c)).catch(()=>{}));if(d.status==="ended"){unsub();cleanup()}});setTimeout(()=>unsub(),300000)}catch(e){setError(e instanceof Error?e.message:"Could not start call.");cleanup()}};
 const accept=async()=>{if(!user||!incoming||!incomingId)return;try{setError("");const type=incoming.type,stream=await navigator.mediaDevices.getUserMedia({audio:true,video:type==="video"});local.current=stream;const r=new RTCPeerConnection({iceServers:[{urls:"stun:stun.l.google.com:19302"}]});pc.current=r;stream.getTracks().forEach(t=>r.addTrack(t,stream));const ref=doc(db,"calls",incomingId);r.onicecandidate=e=>{if(e.candidate)setDoc(ref,{calleeCandidates:arrayUnion(e.candidate.toJSON())},{merge:true})};r.ontrack=e=>{remote.current=e.streams[0]||null};await r.setRemoteDescription(new RTCSessionDescription(incoming.offer!));const answer=await r.createAnswer();await r.setLocalDescription(answer);await setDoc(ref,{answer,status:"connected"},{merge:true});setIncoming(null);setActive(type)}catch(e){setError(e instanceof Error?e.message:"Could not accept call.");cleanup()}};
 const reject=async()=>{if(incomingId)await setDoc(doc(db,"calls",incomingId),{status:"ended"},{merge:true});setIncoming(null);setIncomingId("")};
 const end=async()=>{if(callId.current)await setDoc(doc(db,"calls",callId.current),{status:"ended"},{merge:true});cleanup()};
 if(!user||!selected)return null;
 return <><div className="call-actions"><button title="Voice call" onClick={()=>void start("voice")}>📞</button><button title="Video call" onClick={()=>void start("video")}>📹</button></div>{incoming&&<div className="call-overlay"><div className="call-card"><div className="call-avatar">{incoming.type==="video"?"📹":"📞"}</div><b>Incoming {incoming.type} call</b><small>Someone wants to talk with you.</small><div><button className="accept" onClick={()=>void accept()}>Accept</button><button className="reject" onClick={()=>void reject()}>Decline</button></div></div></div>}{active&&<div className="call-overlay"><div className="call-card active-call"><div className="call-avatar">{active==="video"?"📹":"📞"}</div><b>{active==="video"?"Video":"Voice"} call</b><small>Connected / waiting for the other person…</small><div className="call-controls"><button onClick={()=>{local.current?.getAudioTracks().forEach(t=>t.enabled=muted);setMuted(!muted)}}>{muted?"🔇":"🎙️"}</button>{active==="video"&&<button onClick={()=>{local.current?.getVideoTracks().forEach(t=>t.enabled=!camera);setCamera(!camera)}}>{camera?"📷":"🚫"}</button>}<button className="reject" onClick={()=>void end()}>☎ End</button></div></div></div>}{error&&<div className="toast error">{error}</div>}</>;
}
